/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoOrderNumberRouteImport } from './routes/pedido.$orderNumber'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin/unauthorized'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin/pagamentos'
import { Route as AuthenticatedAdminMidiaRouteImport } from './routes/_authenticated/admin/midia'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin/faq'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAvaliacoesRouteImport } from './routes/_authenticated/admin/avaliacoes'
import { Route as AuthenticatedAdminPersonalizacaoHomeRouteImport } from './routes/_authenticated/admin/personalizacao.home'
import { Route as AuthenticatedAdminPaginasTrabalheConoscoRouteImport } from './routes/_authenticated/admin/paginas.trabalhe-conosco'
import { Route as AuthenticatedAdminPaginasQuemSomosRouteImport } from './routes/_authenticated/admin/paginas.quem-somos'
import { Route as AuthenticatedAdminPaginasHomeRouteImport } from './routes/_authenticated/admin/paginas.home'
import { Route as AuthenticatedAdminPaginasFooterRouteImport } from './routes/_authenticated/admin/paginas.footer'
import { Route as AuthenticatedAdminPaginasFaqRouteImport } from './routes/_authenticated/admin/paginas.faq'
import { Route as AuthenticatedAdminPaginasContatoRouteImport } from './routes/_authenticated/admin/paginas.contato'

const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderNumberRoute = PedidoOrderNumberRouteImport.update({
  id: '/pedido/$orderNumber',
  path: '/pedido/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/admin/unauthorized',
  path: '/admin/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMidiaRoute = AuthenticatedAdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAvaliacoesRoute =
  AuthenticatedAdminAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPersonalizacaoHomeRoute =
  AuthenticatedAdminPersonalizacaoHomeRouteImport.update({
    id: '/personalizacao/home',
    path: '/personalizacao/home',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasTrabalheConoscoRoute =
  AuthenticatedAdminPaginasTrabalheConoscoRouteImport.update({
    id: '/paginas/trabalhe-conosco',
    path: '/paginas/trabalhe-conosco',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasQuemSomosRoute =
  AuthenticatedAdminPaginasQuemSomosRouteImport.update({
    id: '/paginas/quem-somos',
    path: '/paginas/quem-somos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasHomeRoute =
  AuthenticatedAdminPaginasHomeRouteImport.update({
    id: '/paginas/home',
    path: '/paginas/home',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasFooterRoute =
  AuthenticatedAdminPaginasFooterRouteImport.update({
    id: '/paginas/footer',
    path: '/paginas/footer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasFaqRoute =
  AuthenticatedAdminPaginasFaqRouteImport.update({
    id: '/paginas/faq',
    path: '/paginas/faq',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaginasContatoRoute =
  AuthenticatedAdminPaginasContatoRouteImport.update({
    id: '/paginas/contato',
    path: '/paginas/contato',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/menu': typeof MenuRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/paginas/contato': typeof AuthenticatedAdminPaginasContatoRoute
  '/admin/paginas/faq': typeof AuthenticatedAdminPaginasFaqRoute
  '/admin/paginas/footer': typeof AuthenticatedAdminPaginasFooterRoute
  '/admin/paginas/home': typeof AuthenticatedAdminPaginasHomeRoute
  '/admin/paginas/quem-somos': typeof AuthenticatedAdminPaginasQuemSomosRoute
  '/admin/paginas/trabalhe-conosco': typeof AuthenticatedAdminPaginasTrabalheConoscoRoute
  '/admin/personalizacao/home': typeof AuthenticatedAdminPersonalizacaoHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/menu': typeof MenuRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/paginas/contato': typeof AuthenticatedAdminPaginasContatoRoute
  '/admin/paginas/faq': typeof AuthenticatedAdminPaginasFaqRoute
  '/admin/paginas/footer': typeof AuthenticatedAdminPaginasFooterRoute
  '/admin/paginas/home': typeof AuthenticatedAdminPaginasHomeRoute
  '/admin/paginas/quem-somos': typeof AuthenticatedAdminPaginasQuemSomosRoute
  '/admin/paginas/trabalhe-conosco': typeof AuthenticatedAdminPaginasTrabalheConoscoRoute
  '/admin/personalizacao/home': typeof AuthenticatedAdminPersonalizacaoHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/menu': typeof MenuRoute
  '/quem-somos': typeof QuemSomosRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/pedido/$orderNumber': typeof PedidoOrderNumberRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/admin/avaliacoes': typeof AuthenticatedAdminAvaliacoesRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/midia': typeof AuthenticatedAdminMidiaRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/paginas/contato': typeof AuthenticatedAdminPaginasContatoRoute
  '/_authenticated/admin/paginas/faq': typeof AuthenticatedAdminPaginasFaqRoute
  '/_authenticated/admin/paginas/footer': typeof AuthenticatedAdminPaginasFooterRoute
  '/_authenticated/admin/paginas/home': typeof AuthenticatedAdminPaginasHomeRoute
  '/_authenticated/admin/paginas/quem-somos': typeof AuthenticatedAdminPaginasQuemSomosRoute
  '/_authenticated/admin/paginas/trabalhe-conosco': typeof AuthenticatedAdminPaginasTrabalheConoscoRoute
  '/_authenticated/admin/personalizacao/home': typeof AuthenticatedAdminPersonalizacaoHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/menu'
    | '/quem-somos'
    | '/trabalhe-conosco'
    | '/admin'
    | '/perfil'
    | '/admin/login'
    | '/admin/register'
    | '/admin/unauthorized'
    | '/pedido/$orderNumber'
    | '/produto/$id'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/faq'
    | '/admin/midia'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/paginas/contato'
    | '/admin/paginas/faq'
    | '/admin/paginas/footer'
    | '/admin/paginas/home'
    | '/admin/paginas/quem-somos'
    | '/admin/paginas/trabalhe-conosco'
    | '/admin/personalizacao/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/menu'
    | '/quem-somos'
    | '/trabalhe-conosco'
    | '/perfil'
    | '/admin/login'
    | '/admin/register'
    | '/admin/unauthorized'
    | '/pedido/$orderNumber'
    | '/produto/$id'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/faq'
    | '/admin/midia'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
    | '/admin/paginas/contato'
    | '/admin/paginas/faq'
    | '/admin/paginas/footer'
    | '/admin/paginas/home'
    | '/admin/paginas/quem-somos'
    | '/admin/paginas/trabalhe-conosco'
    | '/admin/personalizacao/home'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/menu'
    | '/quem-somos'
    | '/trabalhe-conosco'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/admin/login'
    | '/admin/register'
    | '/admin/unauthorized'
    | '/pedido/$orderNumber'
    | '/produto/$id'
    | '/_authenticated/admin/avaliacoes'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/midia'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/paginas/contato'
    | '/_authenticated/admin/paginas/faq'
    | '/_authenticated/admin/paginas/footer'
    | '/_authenticated/admin/paginas/home'
    | '/_authenticated/admin/paginas/quem-somos'
    | '/_authenticated/admin/paginas/trabalhe-conosco'
    | '/_authenticated/admin/personalizacao/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  MenuRoute: typeof MenuRoute
  QuemSomosRoute: typeof QuemSomosRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  PedidoOrderNumberRoute: typeof PedidoOrderNumberRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderNumber': {
      id: '/pedido/$orderNumber'
      path: '/pedido/$orderNumber'
      fullPath: '/pedido/$orderNumber'
      preLoaderRoute: typeof PedidoOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/admin/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/midia': {
      id: '/_authenticated/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AuthenticatedAdminMidiaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/avaliacoes': {
      id: '/_authenticated/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAdminAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/personalizacao/home': {
      id: '/_authenticated/admin/personalizacao/home'
      path: '/personalizacao/home'
      fullPath: '/admin/personalizacao/home'
      preLoaderRoute: typeof AuthenticatedAdminPersonalizacaoHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/trabalhe-conosco': {
      id: '/_authenticated/admin/paginas/trabalhe-conosco'
      path: '/paginas/trabalhe-conosco'
      fullPath: '/admin/paginas/trabalhe-conosco'
      preLoaderRoute: typeof AuthenticatedAdminPaginasTrabalheConoscoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/quem-somos': {
      id: '/_authenticated/admin/paginas/quem-somos'
      path: '/paginas/quem-somos'
      fullPath: '/admin/paginas/quem-somos'
      preLoaderRoute: typeof AuthenticatedAdminPaginasQuemSomosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/home': {
      id: '/_authenticated/admin/paginas/home'
      path: '/paginas/home'
      fullPath: '/admin/paginas/home'
      preLoaderRoute: typeof AuthenticatedAdminPaginasHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/footer': {
      id: '/_authenticated/admin/paginas/footer'
      path: '/paginas/footer'
      fullPath: '/admin/paginas/footer'
      preLoaderRoute: typeof AuthenticatedAdminPaginasFooterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/faq': {
      id: '/_authenticated/admin/paginas/faq'
      path: '/paginas/faq'
      fullPath: '/admin/paginas/faq'
      preLoaderRoute: typeof AuthenticatedAdminPaginasFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paginas/contato': {
      id: '/_authenticated/admin/paginas/contato'
      path: '/paginas/contato'
      fullPath: '/admin/paginas/contato'
      preLoaderRoute: typeof AuthenticatedAdminPaginasContatoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAvaliacoesRoute: typeof AuthenticatedAdminAvaliacoesRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminMidiaRoute: typeof AuthenticatedAdminMidiaRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPaginasContatoRoute: typeof AuthenticatedAdminPaginasContatoRoute
  AuthenticatedAdminPaginasFaqRoute: typeof AuthenticatedAdminPaginasFaqRoute
  AuthenticatedAdminPaginasFooterRoute: typeof AuthenticatedAdminPaginasFooterRoute
  AuthenticatedAdminPaginasHomeRoute: typeof AuthenticatedAdminPaginasHomeRoute
  AuthenticatedAdminPaginasQuemSomosRoute: typeof AuthenticatedAdminPaginasQuemSomosRoute
  AuthenticatedAdminPaginasTrabalheConoscoRoute: typeof AuthenticatedAdminPaginasTrabalheConoscoRoute
  AuthenticatedAdminPersonalizacaoHomeRoute: typeof AuthenticatedAdminPersonalizacaoHomeRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAvaliacoesRoute: AuthenticatedAdminAvaliacoesRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
    AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
    AuthenticatedAdminMidiaRoute: AuthenticatedAdminMidiaRoute,
    AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminPaginasContatoRoute:
      AuthenticatedAdminPaginasContatoRoute,
    AuthenticatedAdminPaginasFaqRoute: AuthenticatedAdminPaginasFaqRoute,
    AuthenticatedAdminPaginasFooterRoute: AuthenticatedAdminPaginasFooterRoute,
    AuthenticatedAdminPaginasHomeRoute: AuthenticatedAdminPaginasHomeRoute,
    AuthenticatedAdminPaginasQuemSomosRoute:
      AuthenticatedAdminPaginasQuemSomosRoute,
    AuthenticatedAdminPaginasTrabalheConoscoRoute:
      AuthenticatedAdminPaginasTrabalheConoscoRoute,
    AuthenticatedAdminPersonalizacaoHomeRoute:
      AuthenticatedAdminPersonalizacaoHomeRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  MenuRoute: MenuRoute,
  QuemSomosRoute: QuemSomosRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  PedidoOrderNumberRoute: PedidoOrderNumberRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
